services:
<<<<<<< HEAD
  books-service:
  f
=======
  books-service2:
>>>>>>> baf01f1f3e68d65bc7048e5711bbc5d53b3d4117
    image: books:latest
    build:
      context: ./booksServer
    restart: always # always restart the container
    environment:
      - MONGO_URL=mongodb://mongo:27017/BooksDB
      - PORT=80
    ports:
      - "5001:8000" # Adjust the port as needed
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:
