services:
  books-service:
    image: books:latest
    build:
      context: ./booksServer
    restart: always # always restart the container
    environment:
      - MONGO_URL=mongodb://mongo:27017/BooksDB
      - PORT=80
    ports:
      - "5001:8000" # Adjust the port as needed
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:
