name: assignment3
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: ./booksServer
          tags: books:latest, ${{ secrets.USERNAME }}/books:latest
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: books
          path: /tmp/image.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      #    1. download image and run it in a container
      - name: Download artifact
        uses: actions/download-artifact@v3 # downloads all artifacts
      - name: Load Docker images from previous workflows
        run: docker load --input books/image.tar
      - name: check books image is loaded
        run: docker image ls
      - name: create a docker network
        run: docker network create books-net
      - name: run mongodb in container
        run: docker run -d -p 27017:27017 --network books-net --name mongodb mongo
      - name: run image in container
        run: docker run -e MONGO_URL="mongodb://mongodb:27017/BooksDB" --network books-net -p5001:8000 books &
      - name: Check container is running
        run: docker ps
      #     2. set up python and pytest environment
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest # not using yet lint checker like ruff
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #      3. run pytest tests and check results
      - name: Test with pytest # additionally use ruff or other lint checkers
        run: |
          cd tests
          pytest -v assn3_tests.py > assn3_test_results.txt
      - name: upload test results
        if: always() # always perform this step even if tests fail, to see results
        uses: actions/upload-artifact@v3
        with:
          name: GH_test_results
          path: tests/assn3_test_results.txt
      #     The following steps will only execute if tests succeeded
      - name: Set DATE
        run: echo "DATE=$(date -I)" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_COURSE_USERNAME }}
          password: ${{ secrets.DOCKER_COURSE_PASSWORD }}
      - name: push image with "latest" and date tags to DH
        run: |
          docker push ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2
          docker tag ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2 \
          ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:${{ env.DATE }}
          docker push \
          ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:${{ env.DATE }}
