name: assignment3
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: ./booksServer
          file: ./Dockerfile
          tags: books:latest, ${{ secrets.USERNAME }}/wordsvr-v2:latest
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: books
          path: /tmp/image.tar
