name: assignment3
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_COURSE_USERNAME }}
          password: ${{ secrets.DOCKER_COURSE_PASSWORD }}
      - name: Build docker image
        run: echo "DATE=$(date -I)" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build -t books-service ./booksServer
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2
          docker push \
          ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:${{ env.DATE }}
